---
- name: awxtest
  hosts: all
  become: yes
  tasks:
    - name: Create Docker service
      docker_swarm_service:
        name: test1
        state: present
        replicas: 3
        placement:
          constraints:
            - "node.role==worker"
        image: "nginx:latest"
        published_ports:
          - target: 80
            published: 8001
